server:
  port: 9051

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  session:
    jdbc:
      table-name: "SESSIONS"
  mvc:
    view:
      prefix: /WEB-INF/view/

      suffix: .jsp

